services: 
  mysql: 
    platform: linux/amd64
    image: mysql:5.7
    container_name: something
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - mysql:/var/lib/mysql:cached
volumes:
  mysql: